# This file tells Google Cloud Build how to deploy the application.
# It can be attached to a variety of triggers, the default being whenever
# someone merges changes to the main branch.
steps:

#
# UI
#
- id: 'ui.base.pull'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args: [
    '-c',
    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui-base:latest || exit 0'
  ]
  waitFor: [ '-' ]
- id: 'ui.pull'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args: [
    '-c',
    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui:latest || exit 0'
  ]
  waitFor: [ '-' ]
- id: 'ui.base.build'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--target', 'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui-base:latest',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui-base:$COMMIT_SHA',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui-base:latest',
    '.',
    '--build-arg', 'NODE_ENV=production'
  ]
  waitFor: [ 'ui.base.pull' ]
  dir: 'ui'
- id: 'ui.runtime.build'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--target', 'runtime',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui:latest',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui:$COMMIT_SHA',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui:latest',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui-base:$COMMIT_SHA',
    '.'
  ]
  waitFor: [ 'ui.pull', 'ui.base.build' ]
  dir: 'ui'
- id: 'ui.push'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui:$COMMIT_SHA',
  ]
  waitFor: [ 'ui.runtime.build' ]

#
# API
#
- id: 'api.pull'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args: [
    '-c',
    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-api:latest || exit 0'
  ]
  waitFor: [ '-' ]
- id: 'api.build'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-api:latest',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-api:$COMMIT_SHA',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-api:latest',
    '.',
    '--build-arg', 'FLASK_ENV=production',
  ]
  waitFor: [ 'api.pull' ]
  dir: 'api'
- id: 'api.push'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-api:$COMMIT_SHA',
  ]
  waitFor: [ 'api.build' ]

#
# PaperSrv
#
- id: 'papersrv.pull'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args: [
    '-c',
    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-papersrv:latest || exit 0'
  ]
  waitFor: [ '-' ]
- id: 'papersrv.build'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-papersrv:latest',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-papersrv:$COMMIT_SHA',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-papersrv:latest',
    '.',
  ]
  waitFor: [ 'papersrv.pull' ]
  dir: 'papersrv'
- id: 'papersrv.push'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-papersrv:$COMMIT_SHA',
  ]
  waitFor: [ 'papersrv.build' ]

#
# Proxy
#
- id: 'proxy.pull'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args: [
    '-c',
    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-proxy:latest || exit 0'
  ]
  waitFor: [ '-' ]
- id: 'proxy.build'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-proxy:latest',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-proxy:$COMMIT_SHA',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-proxy:latest',
    '.',
    '--build-arg', 'CONF_FILE=prod.conf'
  ]
  waitFor: [ 'proxy.pull' ]
  dir: 'proxy'
- id: 'proxy.push'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-proxy:$COMMIT_SHA',
  ]
  waitFor: [ 'proxy.build' ]

#
# Deploy
#
- id: 'config'
  name: 'gcr.io/ai2-reviz/jsonnet'
  args: [
    'eval',
    '-y',
    '--output-file', './webapp.json',
    '--tla-str', 'env=$_ENV',
    '--tla-str', 'uiImage=gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui:$COMMIT_SHA',
    '--tla-str', 'apiImage=gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-api:$COMMIT_SHA',
    '--tla-str', 'proxyImage=gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-proxy:$COMMIT_SHA',
    '--tla-str', 'paperSrvImage=gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-papersrv:$COMMIT_SHA',
    '--tla-str', 'sha=$COMMIT_SHA',
    '--tla-str', 'cause=Automated Skiff Deploy SHA:$COMMIT_SHA BUILD:$BUILD_ID',
    '--tla-str', 'branch=$BRANCH_NAME',
    '--tla-str', 'repo=$REPO_NAME',
    '--tla-str', 'buildId=$BUILD_ID',
    './webapp.jsonnet'
  ]
  dir: '.skiff'
  waitFor: [ '-' ]
- id: 'deploy'
  name: 'gcr.io/ai2-reviz/rudder'
  args: [
    'deploy',
    '-f',
    'webapp.json'
  ]
  dir: '.skiff'
  waitFor: [ 'api.push', 'ui.push', 'proxy.push', 'papersrv.push' ]

substitutions:
  _ENV: staging
images: [
  'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui:latest',
  'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui-base:latest',
  'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-ui-base:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-api:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-api:latest',
  'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-proxy:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-proxy:latest',
  'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-papersrv:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME-papersrv:latest'
]
artifacts:
  objects:
    location: 'gs://skiff-archive/$REPO_NAME-$BRANCH_NAME/$_ENV/$BUILD_ID/$COMMIT_SHA'
    paths: ['.skiff/webapp.json']
