name: ci
on: push
jobs:
  ui:
    # The default is 360 (6 hours).
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.20.0
      - run: npm install
      - run: npm test
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.20.0
      - run: npm install
      - run: ./bin/start_local_db.sh
      - run: npm test
